onlyBuiltDependencies:
  - esbuild
  - sharp
  - spawn-sync
  - unrs-resolver
  - workerd
  - '@tailwindcss/oxide'
  - 'dtrace-provider'

packages:
  - 'extension'
  - 'web'
  - 'packages/*'

catalog:
  '@ianvs/prettier-plugin-sort-imports': ^4.4.0
  eslint: ^9.17.0
  prettier: ^3.4.2
  typescript: ^5.7.2
  tsup: ^8.3.5
  '@types/node': '^22.10.3'
  '@types/react': '^19.1.2'
